title: Intelligence of Stars
email: feng235ping@gmail.com
description: 'And God said, Let there be light:and there was light.'
url: 'http://onlyfeng.com'
github_username: fengxw
future: true
excerpt_separator: '---'
gems:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jemoji
latest_version: 1.2.4
current_node: 6.1.0
current_chrome: 51.0.2704.103
current_v8: 5.1.281.65
sass:
    style: compressed
available_versions:
    - v0.0.1
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
    - {scope: {path: ""}, values: {image: {path: /images/opengraph.png, width: 1200, height: 630}}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
include:
    - _pages
logo: /images/opengraph.png
